// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD30H6g4a7kLeOJGkB06-QE9HgnNeTK1gY',
    appId: '1:425895351885:web:555531a1716c6ea5d1ae04',
    messagingSenderId: '425895351885',
    projectId: 'iti-project-training',
    authDomain: 'iti-project-training.firebaseapp.com',
    storageBucket: 'iti-project-training.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxwl2R3b75vKstGCssbD4BRJdGnX6bTHc',
    appId: '1:425895351885:android:f7c0c66062d8b973d1ae04',
    messagingSenderId: '425895351885',
    projectId: 'iti-project-training',
    storageBucket: 'iti-project-training.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIFdYmv7dNhefq5gna9mWu49pXIaMRChE',
    appId: '1:425895351885:ios:76cf010e6b3e24f1d1ae04',
    messagingSenderId: '425895351885',
    projectId: 'iti-project-training',
    storageBucket: 'iti-project-training.appspot.com',
    iosClientId: '425895351885-p9cjf04pksb7u8dugr1d5kannfoise19.apps.googleusercontent.com',
    iosBundleId: 'com.example.fip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIFdYmv7dNhefq5gna9mWu49pXIaMRChE',
    appId: '1:425895351885:ios:e8c250a003f47df1d1ae04',
    messagingSenderId: '425895351885',
    projectId: 'iti-project-training',
    storageBucket: 'iti-project-training.appspot.com',
    iosClientId: '425895351885-472n06cpa91s1me8pq0g4hj20gsharf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fip.RunnerTests',
  );
}
